import { Inter } from "next/font/google";
import "../styles/index.scss";
import MainMenubar from "@/components/common/header/main-menubar";
import Footer from "@/components/common/footer/footer";
import { montserrat } from "@/helpers/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body suppressHydrationWarning={true} >
        
        <MainMenubar/>
        {children}
        <Footer/>
      
      </body>
    </html>
  );
}
